export const SECONDS_IN_A_MINUTE = 60;
export const MILLISECONDS_IN_A_SECOND = 1000;
export const MILLISECONDS_IN_A_MINUTE =
	MILLISECONDS_IN_A_SECOND * SECONDS_IN_A_MINUTE;
export const MINUTES_IN_AN_HOUR = 60;
export const HOURS_IN_A_DAY = 24;
export const MILLISECONDS_IN_A_DAY =
	MILLISECONDS_IN_A_SECOND *
	SECONDS_IN_A_MINUTE *
	MINUTES_IN_AN_HOUR *
	HOURS_IN_A_DAY;
export const COOKIE_MINUTES = 30;
export const COOKIE_DURATION = SECONDS_IN_A_MINUTE * COOKIE_MINUTES;
export const HALF = 0.5;
export const TOAST_DURATION = 5000;
